# Generated by Django 2.0.4 on 2018-04-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('CALL', 'Call')], max_length=4, null=True),
        ),
    ]
