# Generated by Django 2.0.4 on 2018-04-11 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180411_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
